troglobit/inadyn

README.md, man/inadyn.8, man/inadyn.conf.5, plugins/changeip.c
Hi @troglobit,
I tested the plugin with the new `v2.0-rc1` release, cross compiled for armv7 with musl libc and libressl without problems.
I had to add `--pidfile inadyn/inadyn` and create `/var/run/inadyn/` which is owned by `inadyn:inadyn` in combination with `--drop-privs=inadyn:inadyn`.
Build log: https://gist.github.com/Duncaen/17f3de043bcbb9b8e0e8d7bf5425d2dc
Cheers,
=> Add strato.com plugin

README.md, debian/inadyn.conf, examples/freemyip.conf, man/inadyn.8, man/inadyn.conf.5, plugins/freemyip.c, src/Makefile.am, src/conf.c
I did some tests, and I was able to successfully update my domain at www.freemyip.com. I also tried some negative case scenarios (e.g. wrong token) and it also works as expected.
=> Adding support for freemyip.com

plugins/cloudxns.c, src/Makefile.am
=> Add support for cloudxns.net

README.md, man/inadyn.8, man/inadyn.conf.5, plugins/cloudxns.c, plugins/dnspod.c, src/Makefile.am
https://www.dnspod.cn (Chinese only)
=> Add support for dnspod.cn

README.md
Spotted these in passing, just a quick fix.
=> Fix broken internal links in README.md.

configure.ac, include/ssl.h
Just add another case statement for Solaris's CA trust locations here...
=> Autoconf changes to find Homebrew's CA trust store

plugins/dynv6.c
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>
=> Fix #235: dynv6, unchanged address is also OK status

Dockerfile, README.md
Also updated README.md as the config file location changed inside
the container. Switched from Bind Mount to Host Volume.
=> Added args to './configure' in Dockerfile to fix #243

include/json.h, include/plugin.h, plugins/cloudflare.c, plugins/yandex.c, src/Makefile.am, src/ddns.c, src/json.c
Some work towards resolving #254. Other plugins still need to be converted.
=> Use a setup function to gather data for Cloudflare plugin

plugins/cloudflare.c, src/json.c
I've been spending too much time with garbage collectors and RAII after all. Checked all my mallocs now, should be fine.
=> Cloudflare: Fix memory leaks when parsing JSON

README.md, examples/duckdns.conf
README: added section for duckdns.org in README
New: added example for duckdns.org
=> added example for duckdns.org

src/os.c
This fixes the reaping of zombies and removes the unused 'status' variable and some other cleanups.
=> Set SIGCHLD to SIG_IGN which will reap the children since POSIX.1-2001.

plugins/cloudflare.c
=> Cloudflare: print setup requests/responses at debug verbosity

README.md, plugins/cloudflare.c
=> Cloudflare: Switch to using API tokens and remove global API key support

src/main.c
=> Include studio to get cuserid

src/main.c
Better fix for #287 using modern macos functions
=> Replace obsolete cuserid() with pwent functions

plugins/cloudflare.c
This will create a new record if the zone can be found, but the hostname cannot.
It will set the correct RR type for the query and the update based on the existence of a colon in the string. It works for my tests.
fixes #286
This test is naturally a HACK @SimonPilkington, but most of the other changes should remain as-is once the address contains a type in the struct.
includes and replaces #290
=> Create new record of v4/v6 in Cloudflare if not found

plugins/cloudflare.c
This will set the correct RR type for the query and the update based on the existence of a colon in the string. It works for my tests. 
fixes #286 
This test is naturally a HACK @SimonPilkington, but most of the other changes should remain as-is once the address contains a type in the struct.
=> Cloudflare ipv6 hack

src/gnutls.c, src/openssl.c
This PR addresses where the `SSL_read` and `gnutls_record_recv` would only read 1 application data packet, which would results in incomplete HTTPS response data.
Fixes #319.
=> Fix tls with multiple application data packets

examples/Makefile.am
Add all examples to `Makefile.am`.
=> Update Makefile for examples

src/os.c
See #334 for details.
Fixes #334.
=> Fix pidfile check for reused pid

plugins/freedns.c
Authentication errors when fetching keys were reported as generic
errors, which means they would not properly terminate as a fatal error.
They will now properly result in an  RC_DDNS_RSP_AUTH_FAIL.
Also, log errors with LOG_ERR instead of LOG_DEBUG or LOG_INFO,
so they can be more easily seen by the user.
Reference: issue #535
=> freedns: handle authentication errors as such; improve error logging

include/ddns.h, plugins/generic.c, src/ddns.c, src/main.c
This can reduce size and improve efficiency.
=> Make some arrays static const

README.md, examples/goip.conf, examples/inadyn.conf, plugins/Makefile.am, plugins/goip.c, src/Makefile.am
not much to comment here. just add quick support for goip.de provider
ipv6 support will follow up later
=> add goip.de provider

examples/goip-ipv4-ipv6.conf, examples/goip-ipv6-only.conf, plugins/goip.c
=> ipv6 support for goip.de

plugins/cloudflare.c
usual fix for https://github.com/troglobit/inadyn/issues/316
=> add wildcard support for cloudflare

plugins/Makefile.am, plugins/desec.c, plugins/domaindiscount24.c, plugins/dyndns.c, src/Makefile.am
just another one from a ticket. so custom is not required anymore
=> add myonlineportal.net plugin

plugins/dyndns.c
Domopoli.de
inwx.com
It's DNS (itsdns.de)
Joker.com
more will come after soon as i find time to make them
=> add new dyndns compatible isps

plugins/Makefile.am, plugins/all-inkl.c, plugins/core-networks.c, plugins/dnsever.c, plugins/dnshome.c, plugins/dnsmadeeasy.c, plugins/dnsmax.c, plugins/dyndns.c, plugins/goip.c, src/Makefile.am
and as always here a new bunch of providers. (more to come in future too)
all-inkl.com
core-networks.de
dnsever.com
dnshome.de
dnsmadeeasy.com
dnsmax.com
thatip.com
schokokeks.de
variomedia.de
udmedia.de
=> add new providers

man/inadyn.conf.5
=> Include ipv6@nsupdate.info in man page inadyn.conf

examples/ovh.conf
Adding an exemple ( that I've tested) for ovh
=> Add an config exemple for ovh

README.md, examples/ipv64.conf, plugins/Makefile.am, plugins/ipv64.c
I hope I have integrated everything in the best possible way. 
Added DynDNS provider
https://ipv64.net
Thanks a lot
=> Add IPv64.net DynDNS Provider

plugins/dyndns.c
FYI https://github.com/troglobit/inadyn/issues/478
=> Fix dynu IPv6 issue

README.md, examples/domeneshop.conf, plugins/Makefile.am, plugins/domeneshop.c, src/Makefile.am
Hope everything looks good
Added support for [domene.shop](domene.shop)
=> Added domene.shop provider
