src/ddns.c

The code contains several unconditional log messages about allocating/freeing memory as well as printing the base64 encode of uer:password.
This code puts a condition on these log messages, so they only appear if a certain verbosity is set.

Sanitize log by putting a condition on several debug messages

---

plugins/duckdns.c

Duck DNS changed their response value to "KO". Not sure whether this is
a typo from their part, but a comparison for this value has been added.

Fix Duck DNS support

---

plugins/duckdns.c

duckdns now specifically requires the 'www.' prefix on the server URL.
Otherwise the server responds with "301 Moved permanently", or with "KO", which means "not OK".

Fix DuckDNS plugin

---

configure.ac
src/Makefile.am
src/tcp.c

Hopefully a trivial portability fix :)

Some systems need <time.h> to pull in struct timeval

---

plugins/generic.c

I've redone the patch for you. It should be cleaner and more consistent with the code style too.
Let me know if you need any clarifications.
I'm testing it for my own ddns and it seems to work fine so far.

custom server plugin - fixes for ddns update server url parsing

---

src/os.c

with option like --pidfile /var/run/inadyn.pid, error came out: Failed creating pidfile (/var/run): Is a directory

avoid dirname() breaking original pidfile_name

---

plugins/easydns.c

This corrects the api usage for the easydns plugin.
I also want to note that their documentation states:
> If you do code a client for easyDNS, please email our [support team](mailto:support@easydns.com) so we can keep you informed of any changes, enhancements, bug fixes etc. Also, please be sure to let us know about your client, which platform it runs on, and where our users can download it so we can add it to our dynamic page.

Fix Easy DNS plugin api updates

---

Makefile.am

Adds missing entry for EXTRA_DIST Automake variable.

Distribute CONTRIBUTING.md file in releases.

---

plugins/dyndns.c

As stated in their Wiki, the checkip servers for SPDYN only handle HTTP on port 80.
What confused me after making this edit is that `checkip-ssl` is forced on if a custom `checkip-server` option is specified. The documentation actually makes this clear, but it doesn't sound like the default value (true) would be used when the `checkip-ssl` option is missing.

Disable SSL checkip connections for SPDYN service.

---

src/gnutls.c
src/openssl.c
src/tcp.c

This fixes #186 by not filtering for only IPv4 addresses in `getaddrinfo()`. It catches both checkip and DDNS update connections because of their common `tcp_init()` function.
Tested with both IPv4 and IPv6-only checkip servers and verified that with the new code, the update server is connected to via IPv6.

Support IPv6 for checkip and update server connections

---

.travis.yml
configure.ac
debian/control
src/gnutls.c

While testing with the update API server from `dynu.com`, the received response was never shown in the debug log. After adding some more logging to `ssl_read()` in `gnutls.c`, it turns out that the server is prematurely closing the connection without a proper TLS shutdown message, which is buggy behaviour.
Googling around, I found some similar reports for other software, where the solution on the client-side is to just ignore the GNUTLS_E_PREMATURE_TERMINATION error, just as OpenSSL does by itself. I'm not aware of the exact security implications, but in this case it fixed my update errors with dynu.com.
The log message should also be implemented in `openssl.c`, but I couldn't yet get my head around their error reporting API, and have not even compiled with OpenSSL for testing.

Ignore premature termination in GnuTLS.

---

src/conf.c
src/log.c

The `validate_provider()` and `validate_custom()` functions always accessed the first corresponding section, instead of the last one that was parsed.  Use the `cfg_opt_size()` magic as shown in the libconfuse tutorial.
Strangely, I never got to see any message from the corresponding `cfg_error()` call, just a generic `Parse error in test.conf` message.  Commenting the `cfg_set_error_function()` call made it work on stderr.  gdb never even saw the `conf_errfunc()` being called, and I couldn't step through `cfg_set_error_function()`.
Could this be a problem with my libconfuse version? Ubuntu 17.10 has 3.2+really3.0+dfsg-1.

Fix validation of provider config sections

---

README.md

Replace ipify.com with ipify.org. Wrong domain name to service.

Minor fix of ipify.org domain name

---

HomebrewFormula/inadyn.rb
README.md

The `HomebrewFormula` path will be searched automatically by Homebrew. allowing the commands as shown below.
The "stable version" command won't work until the next release is pushed.
fixes #140

Homebrew formula and custom tap

---

src/cache.c

This hostname is a special case that tells dnsomatic to update
all hostnames linked to the account.  Trying to resolve it causes a
"Failed resolving hostname all.dnsomatic.com: Name or service not known"
error to be logged.

Do not try to resolve the special hostname all.dnsomatic.com

---

src/cache.c

The hostname field contains a tunnel ID rather than a FQDN.

Don't try to resolve hostname for default@tunnelbroker.net (fixes #219)

---

HomebrewFormula/inadyn.rb

This syncs up your tap formula with what they accepted in Homebrew, but retains the ability to build from HEAD for people wanting to track the latest.
When you release a new version just update the SHA and remove the patch ;-)

Sync up with accepted Homebrew formula

---

Dockerfile
README.md

Adding a Dockerfile simplifies deployment of inadyn without having to worry about installing dependencies or out-of-date packages.

Add Dockerfile for inadyn

---

Dockerfile

See the comment in #226. 
The gnutls and libconfuse shared librares are missing in the second stage. Inadyn can't start without them and a certificate store provided by the ca-certificates package.
Sorry about polluting the commit history. The current image runs fine up until you try to load a config, which I've tried with this branch.

Fix missing shared libraries in Docker image.

---

src/openssl.c

Initialization and Deinitialization are deprecated in OpenSSL 1.1. Fixes
compilation when deprecated APIs are compile-time disabled.

Fix compilation without deprecated OpenSSL 1.1 APIs

---

README.md
include/ddns.h
include/jsmn.h
man/inadyn.conf.5
plugins/Makefile.am
plugins/yandex.c
src/Makefile.am

Hi Joachim,
Could you please review and merge these changes. As per issue #250.
Thanks.
Changes:
* increase PASSWORD_LEN to 256 as per PddToken length.
* add Jsmn header only library for JSON processing.
Config notes:
* username should be your domain managed by Yandex DNS.
* password is your PddToken.
* in the hostname parameter please put subdomain (not FQDN).
It should be noted that if hostname does not exist in DNS,
plugin will add it.
For more info please see Yandex PDD API documentation
https://tech.yandex.ru/pdd/doc/concepts/api-dns-docpage/.
Based on the work by https://github.com/dmitrodem.
Signed-off-by: Timur Birsh <taem@linukz.org>

Add Yandex PDD (Yandex.Connect) plugin

---

README.md
plugins/cloudflare.c

It occurred to me it's silly to put the zone name in the username when hostnames can just be FQDNs and thus contain the zone. The config example already tells you to do this, and it's actually currently wrong and will cause the hostname to not be found, so this fixes both of those things.

Cloudflare: extract zone name from FQDN instead of username

---

include/ddns.h

The .ORG TLD cannot be resolved in China, but the .COM one can.  Since it's just a CNAME, this should have no functionality change, except allow Chinese users to also use it.  This has been confirmed by two Chinese users.

Change default DynDNS IP server to the .com TLD address

---

Dockerfile

Can be validated using my docker image on docker hub: https://hub.docker.com/repository/docker/dprus/inadyn
Most importantly this allows me to easily specify "-l debug" when I need to.

Add the ability to specify command line options to inadyn in the Dockerfile

---

include/ddns.h

Enlarge response buffer size to accomodate larger replies
Cloudflare responses were getting truncated at 1023 chars: (lot of hacked in debug)
```
Jan 12 23:08:34  inadyn[69236] <Debug>: Successfully sent HTTPS request!
Jan 12 23:08:34  inadyn[69236] <Info>: called: ret=1023 buf_len=1023 recv_len=-367501560
Jan 12 23:08:34  inadyn[69236] <Info>: body len: 1023 buf_len: 0 buf_size: 1023
Jan 12 23:08:34  inadyn[69236] <Info>: ret: -50 The request is invalid.
Jan 12 23:08:34  inadyn[69236] <Info>: body = 1023: HTTP/1.1 200 OK
Date: Mon, 13 Jan 2020 07:08:34 GMT
Content-Type: application/json
Connection: close
Set-Cookie: __cfduid=dce59156c2b625ff3943f17d5af981c8e1578899314; expires=Wed, 12-Feb-20 07:08:34 GMT; path=/; domain=.api.cloudflare.com; HttpOnly; SameSite=Lax
CF-Ray: …
```

Ensure 8kb DDNS response buffer size

---

README.md

The instructions provided with the cloudflare example don't work:
```
{"success":false,"errors":[{"code":0,"message":"Actor 'com.cloudflare.api.token.*******' requires permission 'com.cloudflare.api.account.zone.list' to list zones"}],"messages":[],"result":null}
```
I believe my changes are an improvement.
Also replaced tabs with spaces.

List all required permissions for Cloudflare

---

plugins/cloudflare.c

The debugging here is a bit excessive but it shows the problem:
```
{"result":[{"id":"aad8dfa1218ae29dbdfe5fa9569cb682","name":"netconsonance.com","....snip
Jan 14 00:39:32  inadyn[64113] <Debug>: ID position in string: 3
Jan 14 00:39:32  inadyn[64113] <Info>: token->start: 18
Jan 14 00:39:32  inadyn[64113] <Info>: token->end: 50
Jan 14 00:39:32  inadyn[64113] <Info>: length: 32
Jan 14 00:39:32  inadyn[64113] <Debug>: ID value: aad8dfa1218ae29dbdfe5fa9569cb68
Jan 14 00:39:32  inadyn[64113] <Debug>: Cloudflare Zone: 'netconsonance.com' Id: aad8dfa1218ae29dbdfe5fa9569cb68
```
If you add one to the length calculation it trips over the dest_size limit, so the only fix is to add one to the length when calling `strlcpy()`
```
{"result":[{"id":"aad8dfa1218ae29dbdfe5fa9569cb682","name":"netconsona …
```

Fix string copy length issue in cloudflare provider

---

plugins/cloudflare.c

The patch converts the Cloudflare plugin to use a new 'data' field, reserved for plugins, in the setup() and request() callbacks.  This way we can have one Inadyn instance serve multiple Cloudflare accounts, i.e., no more global variables.

Concert Cloudflare to use new ddns_info_t:data field in setup() and request()

---

include/ssl.h
man/inadyn.conf.5
src/conf.c
src/gnutls.c
src/main.c
src/openssl.c

HTTPS certificates are only valid within specified time windows, so on systems without hardware real-time clock and default bootup time far in the past, false-positive validation fail is expected.
When this setting is enabled, i.e. true, then inadyn will only issue a warning that the certificate is not valid yet. By default this setting is disabled, because security matters.

Add broken-rtc = <true | false> .conf file setting

---

include/error.h
plugins/cloudflare.c
plugins/common.c
src/ddns.c
src/error.c
src/http.c

Useful for human-readable logging and can be used for additional logic of custom plugins/further script actions.
For example it's currently used for asuscomm.com in https://github.com/RMerl/asuswrt-merlin.ng

Add common authentication failure error code

---

plugins/freedns.c

bufferstr[] was getting strlcat() without first being initialized,
causing the hash to contain random binary content at the start
of it (and FreeDNS auth to randomly fail).
Credits to themiron for optimizing that code section, which
also resolves the original issue in addition to being more
efficient.

plugins: fix use of non-initialized buffer in freedns hash generation

---

Dockerfile

Hi @troglobit . Thank you for the inadyn project. I find it very usefull!
I have two suggestions to improve the Dockerfile of your project.
- Instead of calling git in Dockerfile, use COPY to take all the files from the actual commit and use these files to build inadyn. In the future, it will allow to checkout to a tag version (v2.6 for example) and recreate a Docker image with version 2.6 of the code. Actually, if I take any commit that contains the Dockerfile and I build the image, it always build the latest commit of master.
- Use another alpine build stage to copy only the result of the build in the final Docker image. It will create a slightly smaller image as the sources will not be in a layer of the final image.
I take only the executable and doc folder from the build result. I …

Improvements for Dockerfile

---

include/ddns.h
include/os.h
man/inadyn.8
src/ddns.c
src/main.c
src/os.c

Hi,
this pull request always runs the exec handler.
The option `--exec-mode=[compat|event]` is introduced. When set to event the script foo, in `--exec foo`, would be called with `$1` set to one of: `update`, `nochg`, `error`. `$2` provides the return code of the send update and `$3` the corresponding error message.
When `--exec-mode` is not set or set to `compat` the script foo would be called as-is today.

Always run exec handler

---

README.md
plugins/cloudflare.c

Automatic zone name extraction was buggy and did not handle third-level
domain zones correctly.
Fixes https://github.com/troglobit/inadyn/issues/312

Cloudflare: Get zone name from username field in the config

---

README.md

Tokens with permissions only for a specific zone can now fetch the id
for that zone, so this workaround is no longer necessary.

Cloudflare: remove workaround for fixed bug

---

src/ddns.c

There is a small typo in src/ddns.c.
Should read `unnecessary` rather than `unnnecessary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, unnnecessary -> unnecessary

---

.github/workflows/build.yml

This PR uses GitHub Actions to build multi-arch docker image and push to docker hub.
Steps to merge this PR:
1. Go to https://hub.docker.com/repository/docker/troglobit/inadyn/builds and disable automatic build.
2. Go to https://github.com/troglobit/inadyn/settings/hooks and remove docker hub webhook.
3. Go to https://hub.docker.com/settings/security and create a new access token.
4. Go to https://github.com/troglobit/inadyn/settings/secrets/actions and add two secrets.
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN
5. Merge this PR.
Fixes #315.

Use github action to build multi-arch docker image

---

Dockerfile

This PR uses a more idiomatic way to handle command line arguments for container entrypoint.
Currently: `docker run --env "INADYN_OPTS=--help" troglobit/inadyn`
With this PR: `docker run troglobit/inadyn --help`
Another small change is that it will be only one running process (inadyn) instead of two (sh + inadyn).

Update docker entrypoint

---

src/conf.c

I'm not sure if this is the best solution, but from the existing code comment I assume that all options available in a provider configuration section should also apply to a custom section.  The `ttl` and `proxied` options were added recently and are not present in the custom options descriptor array.
So copying these two lines from above fixes the messages reported in #340 and makes inadyn work for me without complaints.

Add missing provider option definitions to custom section options (fixes #340)

---

src/Makefile.am
src/gnutls_base64.c
src/openssl_base64.c

These should be better optimized than the generic versions bundled
with inadyn, and reduce the size of the final binary.

Use the OpenSSL or GnuTLS base64 functions

---

configure.ac
src/Makefile.am
src/gnutls_hash.c
src/openssl_hash.c

These are generally better optimized than the generic versions bundled
with inadyn, and significantly reduce the size of the final binary.

Use the OpenSSL or GnuTLS hash functions

---

src/plugin.c

This was intended to handle the case where the plugin name was not set,
but all plugins supply a name so it was never used. To ensure this
remains true, add an assert call.

Remove some dead code in plugin_register()

---

README.md
configure.ac
include/log.h
src/conf.c
src/error.c
src/log.c
src/main.c

Using the --enable-reduced configure option, a smaller binary is produced by
eliminating verbose log messages and error strings and eliminating config file
checking & some config backward compatibility.

Add an option to build a smaller binary for embedded applications

---

examples/google-domains.conf

[Config in Google Domains Documentation](https://support.google.com/domains/answer/6147083?hl=en#zippy=%2Cset-up-a-client-program-on-your-gateway-host-or-server) is out of date. Requesting add config example since their documentation and support is atrocious. Tested and was able to connect with this config today.

add google domains example

---

plugins/cloudflare.c
src/ddns.c

Fix the following build failures raised since version 2.8 and https://github.com/troglobit/inadyn/commit/1928d7a80390a2ef651a32d5723531fca51384d4:
```
ddns.c: In function 'is_address_valid':
ddns.c:193:2: error: 'for' loop initial declarations are only allowed in C99 mode
for (size_t i = 0; i < NELEMS(except); i++) {
^
```
Fixes:
- http://autobuild.buildroot.org/results/9323cc7afceff75f7d41ff161b8d0ec9aefa164a
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

fix build with gcc 4.8

---

inadyn.service.in

Generally this is considered good practice for scripts (more often read than written).

Use long version of commandline arguments for systemd service

---

README.md

Hello there.
I'm a volunteer opensource contributor for various projects, mainly related to your project inadyn which we recently updated from our old inadyn 1.96ADV to inadyn 2.9.1 in DD-WRT as you may know its a 3rd party Firmware for many popular consumer routers.
We have simplified the user interface in some cases (providers) and fixed bugs on our side (not related to inadyn directly but our implementation) making sure it works and thus far all is coming along fine and obviously old inadyn configs are now incompatible and not an issue and was expected.
In any case we refer our users to your documentation on the setup side of thisngs and I noticed some of this alignment issues poked my eyes, so here in to unpoking them ;)

readme.md: minor indenting fixes

---

README.md
plugins/generic.c

This will automatically accept the responses for DNSMadeEasy DDNS service. 
It makes sense to have this word on the list of OK responses so inadyn accepts it out of the box with dnsmadeeasy or other providers.
Related-To: https://dnsmadeeasy.com/technology/dynamic-dns (bottom)

chore: add 'success' as a valid response by default

---

plugins/Makefile.am
plugins/dnspod.c
plugins/dyndns.c
plugins/mydns.c
plugins/myonlineportal.c
plugins/namecheap.c
plugins/regfish.c
plugins/twodns.c
src/Makefile.am

once again:
changes: 
dnspod.cn ipv6 support, 
api change for myonlineportal.net (own plugin now)
new providers:
moniker.com
dyndns.it
infomaniak.com
oray.com
simply.com
mydns.jp
namecheap.com
regfish.de
twodns.de

add new providers

---

include/http.h
include/ssl.h
include/tcp.h
plugins/cloudflare.c
plugins/cloudxns.c
plugins/dnspod.c
plugins/freedns.c
plugins/yandex.c
src/cache.c
src/ddns.c
src/gnutls.c
src/http.c
src/mbedtls.c
src/openssl.c
src/tcp.c

for ipv4 providers we should enforce ipv4 mode and for ipv6 the same as ipv6
background. some providers implement a rate limit. since we update ipv4 and ipv6 in 2 steps, this leads often to a delay
until the second address is updated. with 2 different ips we may prevent this issue.
in case the enforced mode isnt operational, we fall back to auto mode to allow a fallback to the other connection mode.
on any error on first attempt no log is shown, since we fallback anyway.
falling back is required anyway. as discovered some providers do not have AAAA records for the api servers (easydns for instance) but allow to update AAAA record on the ddns host
please comment what you think 

RFC: enforce desired tcp operation mode (v4 or v6)

---

plugins/desec.c

desec.io only supports updates via `update.dedyn.io` and `update6.dedyn.io`.
See https://desec.readthedocs.io/en/latest/dyndns/update-api.html

fix desec.io server_name

---

plugins/dnshome.c
plugins/mydns.c
plugins/twodns.c

This PR fixes format string errors in three recently added plugins.  The first commit I'm not too sure about since I don't know if the providers require basic auth or not.
Hopefully @BrainSlayer can have a look and confirm my fixes.

Format string fixes for new plugins

---

man/inadyn.conf.5

While possibly not commonly used by checkip servers, query string parameters are supported in `inadyn` via `checkip-path`.

Mention that checkip-path supports query params

---

.github/workflows/container.yml

Ever since first adding support for building containers, PR #329, In-a-Dyn container images have applied the `:latest` tag wrong.
According to [best practices][1], the `:latest` tag should be applied to the latest release of a software, not the latest build.
This patch changes that, using [GitHub action variables][2] to set up a list of tags or generate a version for tagging.  The docker builders take multiple tags [separated with comma][3] (',') and for GHCR we simply use a for-loop.
[1]: https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/
[2]: https://docs.github.com/en/actions/learn-github-actions/variables
[3]: https://github.com/docker/build-push-action

Fix #421: use Docker :latest tag only for latest In-a-Dyn release

---

Dockerfile

This is just to have a peace of mind, we just always tell `Alpine APK` to always update the list of available packages before installing dependencies.

Always update to get the latest list of available packages.

---

man/inadyn.conf.5
plugins/cloudflare.c

Fixes #451.
Cloudflare configuration now accepts a _Cloudflare identifier_ in `hostname` allowing `inadyn` to update a round-robin dns hostname (a hostname with multiple ip address).
Sample:
```
provider default@cloudflare.com {
username = "THE_DOMAIN"
password = "THE_TOKEN"
hostname = "a2a279c0aa5f48ab964a6ccc4258f020"
ttl = 60
proxied = false
}
```
Changes in source code:
- expands `get_id` to `json_extract`: can extract any property from `json` (not just `id`).
- if `hostname` looks like a cloudflare id (32 chars and only hex digits) query the `dns_records` endpoint directly by `id`.
Related: https://developers.cloudflare.com/dns/manage-dns-records/how-to/round-robin-dns

Fix #451: Adds support for round-robin records to Cloudflare.

---

src/ddns.c

As per [this comment](https://github.com/troglobit/inadyn/issues/450#issuecomment-1739524213) on #450.
There are 3 methods of IP resolution, in order of priority:
- `get_address_cmd()`
- `get_address_iface()`
- `get_address_remote()`
Changes in source code:
- Moves the checks for "is this method configured?" to outside of `get_address_cmd()` and `get_address_iface()`;
- When found one method configured stops looking for other methods if an error occurs;
- `get_address_remote()` (the latest, in order) is unchanged.

Fix #450: Do not use an IP resolution method different than the one specified in configuration.

---

README.md
plugins/namecheap.c

This PR fixes the 2 problems with the current namecheap support and also updates the `README.md` to reflect that.
-----
The first problem stems from the `good` and `nochg` strings no longer getting sent back, making `inadyn` think the request failed (while it might not have).
The example in the `README.md` on the other hand will always succeed, since `true` is always in the response, even if it failed. Refer to the examples below.
I have decided to replace both with a check for `<ErrCount>0</ErrCount>`.
<details><summary>faulty response</summary>
```xml
<?xml version="1.0" encoding="utf-16"?>
<interface-response>
<Command>SETDNSHOST</Command>
<Language>eng</Language>
<ErrCount>1</ErrCount>
<errors>
<Err1>Passwords do not match</Err1>
</errors>
<ResponseCount>1</ResponseCount>
<responses> …
```

Fix support for namecheap

---

examples/porkbun-ipv4-only.conf
examples/porkbun-ipv6-only.conf
plugins/Makefile.am
plugins/porkbun.c
src/Makefile.am

This pull request aims to adapt Inadyn's code so that it can use the PorkBun API, a dynamic DNS provider. To do this, the following functions have been modified:
- setup: to get zone ID and hostname ID using PorkBun API
- request: to send DNS update request using PorkBun API
- response: to check the PorkBun API response status code
- json_extract: to extract the value of a JSON key from the PorkBun API response
and other functions
A new data structure has also been defined to store the information from PorkBun's dynamic DNS system, and corresponding values have been assigned to the structure's fields.

Added porkbun support

---

plugins/dnshome.c
plugins/ipv64.c

The check for whether the name contains "ipv6" is not necessary for the plugins "dnshome" and "ipv64", as the code path for both branches is the same.
Furthermore the check is rather confusing in the context of the provider named "ipv64.net", as "ipv6" is also contained in the provider name itself.

Remove duplicate branches in request of plugins

---

README.md

`inadyn` has now been added to [MacPorts](https://www.macports.org).
This PR adds information to the README on installing it via that method.
https://ports.macports.org/port/inadyn/

Add information on installing via MacPorts

---

include/ddns.h
plugins/cloudflare.c
plugins/core-networks.c
plugins/dnspod.c
plugins/freedns.c
plugins/porkbun.c
src/cache.c
src/ddns.c

The issue was occurring while checking whether the provider name contained
"ipv6" as an indication for whether to use IPv4 or IPv4. The check
confused a definition like "ipv4@ipv64.net" to use IPv6 due to having
"ipv6" in the name.
To address the issue we changed the check to whether the prefix of
the provider name is "ipv6".
While doing so, we factored out this check into a own function taking
a ddns_info_t * struct as an argument.

Fix issue with detection whether to use ipv6 or ipv4

---

src/main.c

It's unexpected that inadyn --help would try to create a directory, or that a --cache-dir argument would be required when using --check-config before running the service with --cache-dir
This might incorrectly print a default of ~/.cache/inadyn in --help if /var/cache/inadyn is missing, and then fail to create the directory and fallback to ~/.inadyn when actually running it, but this is a problem that already exists when running inadyn first with no ~/.cache dir and creating ~/.cache later: after a reset the directory would change with no apparent reason.
A further improvement might check if ~/.inadyn exists but not ~/.cache/inadyn and use that.

Avoid creating cache directory for usage or check-config

---

src/main.c

If the service uses the default /var/cache/inadyn directory, then that
directory will have been created and there is no problem, but if using
an alternate directory with --cache-dir is used then it must also be
passed to any --check-config invocation as well lest this error message
is printed:
```
Cannot create fallback cache dir: No such file or directory
```
However, there already is another message that is only printed on
service start and not on check-conf:
```
inadyn[1902671]: No write permission to /var/cache/inadyn: Permission denied
inadyn[1902671]: Cannot guarantee DDNS server won't lock you out for excessive updates.
```
So just remove the 'Cannot create fallback' message.
------------------
This is a follow-up on #522 -- sorry for bugging you on a closed PR there!
You've …

Remove log when /var/cache/inadyn is missing and no $HOME
